###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure 
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
service:  
  type: NodePort
  webuiPort: 4414  
  serverlistenerPort: 7800
  nodelistenerPort: 7080
image:
  repository: master.cfc:8500/default/iibv10fp9image
  tag: dev
  pullPolicy: IfNotPresent
license: "Not accepted"
nodename: "IIB_NODE"
servername: "IIB_SERVER"
